# Настройки плагина RestDuels

# Настройки миров
worlds:
  # Список миров, в которых проводятся дуэли
  duel-worlds:
    - "duels"

# Настройки дуэлей
duel:
  # Убивать ли игрока при выходе в мире дуэлей
  kill-on-quit: true

  # Радиус защиты спавна (в блоках)
  spawn-protection-radius: 10.0

  # Время сбора ресурсов после дуэли (в секундах)
  resource-collection-time: 60

teleport:
  # Проверять безопасность локации перед телепортацией
  check_safety: true
  # Задержка телепортации при входе (в тиках)
  join_delay: 80
  # Команда для телепортации на спавн
  spawn-command: "spawn %player%"  # Используйте здесь команду, телепортирующую в мир spawn

# Настройки арен для дуэлей
arenas:
  arena1:
    world: duels
    x1: -87.30018007256366
    y1: 119.0
    z1: -114.75988488133085
    x2: -88.31251058335639
    y2: 120.0
    z2: -59.24535472403113
    yaw1: -5.497395E-7
    pitch1: 1.968764
    yaw2: -179.94548
    pitch2: 1.9125082
  arena2:
    world: duels
    x1: -420.5
    y1: 112.0
    z1: -120.5
    x2: -421.4112968822149
    y2: 113.0
    z2: -50.10957272635852
    yaw1: 0.7309483
    pitch1: 0.28105247
    yaw2: 180.73279
    pitch2: 0.22480202
  arena3:
    world: duels
    x1: -444.4568527402152
    y1: 83.0
    z1: 153.61803699964517
    x2: -444.93801741186866
    y2: 83.0
    z2: 227.52399839045688
    yaw1: 0.44942975
    pitch1: -2.0816371
    yaw2: -178.42734
    pitch2: -1.9128788

# Настройки дуэльных режимов
duel_types:
  normal:
    name: "Обычная дуэль"
    description: "Инвентарь выпадает"
  ranked:
    name: "Дуэль без потерь"
    description: "Инвентарь сохраняется"

# Настройки таймеров (в секундах)
timers:
  search-time: 30     # Время поиска соперника
  cancel-time: 8      # Время для отмены дуэли
  duel-time: 20       # Время дуэли в минутах

# Настройки сохранения локаций
location_saving:
  # Включить сохранение локаций в файл
  save_to_file: true
  # Время в часах, после которого локация считается устаревшей
  expiration_time: 72
  # Задержка перед телепортацией после входа (в тиках, 20 тиков = 1 секунда)
  teleport_delay: 5
  # Очищать устаревшие локации при загрузке плагина
  clean_old_locations: true
  # Сохранять локацию при выходе игрока во время дуэли
  save_on_quit: true
  # Телепортировать игрока на сохраненную локацию после респавна
  teleport_after_respawn: true
  # Задержка телепортации после респавна (в тиках)
  respawn_teleport_delay: 5
  # Сохранять оригинальную локацию поиска дуэли
  preserve_original_location: true

# Настройки респавна
respawn:
  # Принудительно восстанавливать игрока в исходное местоположение после смерти в дуэли
  force_original_location: true
  # Задержка телепортации после респавна (в тиках)
  teleport_delay: 5
  # Игнорировать точку респавна сервера и телепортировать на исходную локацию
  ignore_server_respawn: true

# Настройки режима бога
godmode:
  # Отключать ли режим бога во время дуэлей
  disable-during-duel: true

  # Восстанавливать ли режим бога после дуэли
  restore-after-duel: true

# Настройки команд
commands:
  # Разрешенные команды во время дуэли
  allowed-during-duel:
    - "/hub"
    - "/lobby"
    - "/leave"
    - "/quit"
    - "/duel return"

  # Сообщение при блокировке команды
  block-message: "&cКоманды заблокированы во время дуэли!"

  # Приоритет блокировки команд (LOWEST, LOW, NORMAL, HIGH, HIGHEST, MONITOR)
  block-priority: "LOWEST"

# Настройки восстановления
restoration:
  restore-on-enter: true  # Восстанавливать арену, когда игроки входят на нее
  # Включить принудительное восстановление арены через команду, лучше оставить
  force-command-restore: true
  # Задержка перед принудительным восстановлением (в тиках, 20 тиков = 1 секунда)
  force-restore-delay: 80
  # Количество блоков, обрабатываемых за один тик при восстановлении (0 = без ограничений)
  blocks-per-tick: 20000
  # Автоматически восстанавливать арены после дуэли
  auto-restore: true
  # Автоматически захватывать состояние арены перед дуэлью
  # Можно установить false, если вы предпочитаете использовать заранее сохраненное состояние
  auto-capture: false
  # Блокировать арену во время восстановления
  block-during-restore: true

building:
  # Разрешить строительство на аренах во время дуэлей
  allow-building: true

  # Разрешить ломание только построенных игроками блоков
  allow-breaking-only-player-blocks: true

  # Отключить урон от TNT на арене
  disable-tnt-damage: false

  # Максимальное количество блоков, которое может построить игрок (0 = без ограничений)
  max-blocks-per-player: 0

# Настройки сообщений
messages:
  prefix: "&x&D&C&8&5&1&4&lR&x&E&0&9&4&1&2&le&x&E&4&A&4&0&F&ls&x&E&8&B&3&0&D&lt&x&E&C&C&2&0&A&lD&x&F&0&D&1&0&8&lu&x&F&4&E&1&0&5&le&x&F&8&F&0&0&3&ll&x&F&C&F&F&0&0&ls &e>>&r "
  loser-returned: "&cВы проиграли и были возвращены на исходную позицию."
  winner-returned: "&aВы были возвращены на исходную позицию с собранными вещами."
  flight-disabled: "&cПолет запрещен во время дуэли!"
  duel-started: "&aДуэль началась! Удачи!"
  cancel-duel-message: "&eДля отмены дуэли нажмите на кнопку ниже в течение &c%time% &eсекунд."
  cancel-search-button: "&c[Отменить поиск дуэли]"
  cancel-search-message: "&eДля отмены поиска дуэли нажмите на кнопку ниже в течение &c30 &eсекунд."
  opponent-found: "&eНайден соперник! У вас есть &c8 секунд &eдля отмены дуэли."
  opponent-cancelled: "&cПротивник отменил дуэль!"
  duel-ended: "&aДуэль закончилась! Победитель: &e%winner%"
  duel-timeout: "&cВремя дуэли истекло! Вы были возвращены обратно."
  searching: "&eПоиск соперника... &7(%time% сек)"
  no-opponent: "&cСоперник не найден! Вы были возвращены обратно."
  cancel-button: "&c[Выйти с дуэли]"
  duel-cancelled: "&cДуэль отменена!"
  player-in-duel: "&cИгрок уже участвует в дуэли!"
  duel-draw: "&eВремя дуэли истекло! &6Объявлена ничья."
  opponent-quit: "&aВы победили! Противник вышел с сервера."
  opponent-killed: "&aВы победили! Противник был убит."
  match-cancelled-quit: "&cПротивник вышел с сервера. Дуэль отменена."
  commands-blocked: "&cВы не можете использовать команды во время дуэли!"
  godmode-disabled: "&cРежим бога был временно отключен для дуэли!"
  godmode-restored: "&aРежим бога был восстановлен!"
  returned-after-disconnect: "&eВы были телепортированы на спавн после выхода с сервера во время дуэли."
  duel-world-unauthorized: "&cВы не можете телепортироваться в мир дуэлей без активной дуэли!"
  teleported-to-spawn: "&eВы были телепортированы на спавн, так как находились в мире дуэлей без активной дуэли."
  arena-boundary-warning: "&cВы выходите за пределы арены! Вернитесь обратно!"
  arena-boundary-teleport: "&cВы вышли за пределы арены! Вы были телепортированы обратно."
  returned-to-location: "&eВы были возвращены на исходную позицию после переподключения."
  returned-to-spawn: "&eВаша исходная позиция недоступна. Вы были телепортированы на спавн."
  player-killed-on-quit: "&c%player% был убит за выход во время дуэли!"
  menu-closed-pvp: "&cМеню дуэлей закрыто из-за входа в PvP."
  notify-menu-close: false
  delay-collect: "&eУ вас есть &c60 секунд &eдля сбора ресурсов."
  early-return-button: "&a[Телепортироваться досрочно]"
  winner-collect: "&aВы победили! У вас есть &c60 секунд &aдля сбора вещей."
  early-return-success: "&aВы были досрочно телепортированы на исходную позицию."
  early-return-active-duel: "&cВы не можете использовать досрочный возврат во время активной дуэли! Дождитесь окончания дуэли или используйте /hub."
  early-return-no-task: "&cУ вас нет активной задачи возврата."
  cannot-cancel-active-duel: "&cВы не можете выйти из активной дуэли! Используйте /hub, чтобы покинуть сервер."

# Настройки GUI
gui:
  # Название меню
  title: "Меню Дуэлей"

  # Размер меню (строки * 9)
  size: 5

  # Предметы меню (можно добавлять сколько угодно)
  items:
    # Фоновое стекло красное
    red_glass:
      enabled: true
      # Можно указать отдельные слоты через запятую или диапазоны через дефис
      slots: "0-8,9,17,18,26,27,35,36-44"
      material: "RED_STAINED_GLASS_PANE"
      name: " "
      glow: false
      # Лор можно не указывать, если он не нужен

    # Фоновое стекло серое
    gray_glass:
      enabled: true
      slots: "10,12,14,16,19,21,23,25,28,30,32,34"
      material: "LIGHT_GRAY_STAINED_GLASS_PANE"
      name: " "
      glow: false

    # Обычная дуэль
    normal_duel:
      enabled: true
      slots: "11"
      material: "COMPASS"
      name: "&c[X] &6Поиск обычной дуэли"
      glow: false
      lore:
        - "&6→ Нажмите, чтобы начать поиск"
        - ""
        - "&f[ЛКМ] &6Начать поиск"
        - "&f[ШИФТ+ЛКМ] &6Отменить поиск"
        - ""
        - "&c• &fПараметры"
        - "&6▶ &fСлучайный соперник"
        - "&6▶ &fИнвентарь выпадает"
        - "&6▶ &fНаграды нет"
        - ""
        - "&eЧеловек в поиске: &f%normal_queue_size%"
        - "&eСвободных арен: &f%free_arenas%&e/&f%total_arenas%"
        - "&eИгроков в очереди на арену: &f%arena_queue_size%"
      # Действие при клике (normal_duel, ranked_duel, stats, command:имя_команды, close)
      action: "normal_duel"

    # Рейтинговая дуэль
    ranked_duel:
      enabled: true
      slots: "15"
      material: "COMPASS"
      name: "&c[X] &6Поиск venom дуэли"
      glow: false
      lore:
        - "&6→ Нажмите, чтобы начать поиск"
        - ""
        - "&f[ЛКМ] &6Начать поиск"
        - "&f[ШИФТ+ЛКМ] &6Отменить поиск"
        - ""
        - "&c• &fПараметры"
        - "&6▶ &fРавный соперник"
        - "&6▶ &fИнвентарь не выпадает"
        - "&6▶ &fВлияет на рейтинг"
        - ""
        - "&eЧеловек в поиске: &f%ranked_queue_size%"
        - "&eСвободных арен: &f%free_arenas%&e/&f%total_arenas%"
        - "&eИгроков в очереди на арену: &f%arena_queue_size%"
      action: "ranked_duel"

    # Статистика игрока
    player_stats:
      enabled: true
      slots: "22"
      material: "PLAYER_HEAD"
      use_player_head: true
      name: "&6Ваша статистика"
      glow: false
      lore:
        - "&e&lПобед: &f%wins%"
        - "&c&lСмертей: &f%deaths%"
        - "&e&lK/D: &f%kd%"
        - "&e&lПроцент побед: &f%win_rate%%"
        - ""
        - "&aНажмите для просмотра подробной статистики"
      action: "stats"

    # Пример информационной книги
    info_book:
      enabled: true
      slots: "4"
      material: "BOOK"
      name: "&eИнформация о дуэлях"
      glow: true
      lore:
        - "&7Дуэли - это способ сразиться"
        - "&7с другими игроками один на один"
        - ""
        - "&6Выберите тип дуэли и начните поиск!"
      # Без действия - просто декоративный элемент

    # Кнопка закрытия меню
    close_button:
      enabled: true
      slots: "40"
      material: "BARRIER"
      name: "&cЗакрыть меню"
      glow: false
      lore:
        - "&7Нажмите, чтобы закрыть меню"
      action: "close"

    # Пример выполнения произвольной команды
    command_button:
      enabled: true
      slots: "13"
      material: "DIAMOND_SWORD"
      name: "&bТоп игроков"
      glow: true
      lore:
        - "&7Нажмите, чтобы посмотреть"
        - "&7топ игроков по дуэлям"
      action: "command:duel top"

# Настройки заголовков и сообщений на экране
titles:
  duel-draw:
    title: "&6Ничья!"
    subtitle: "&eВремя дуэли истекло"
    fadeIn: 10
    stay: 60
    fadeOut: 20
  searching:
    title: "<gradient:FCFF00:FF9900>Поиск соперника</gradient>"
    subtitle: "&eОсталось: &c%time% &eсекунд"
    fadeIn: 10
    stay: 20
    fadeOut: 10
  no-opponent:
    title: "&cСоперник не найден!"
    subtitle: "&eВы возвращены на исходную позицию"
    fadeIn: 10
    stay: 60
    fadeOut: 20
  duel-started:
    title: "<gradient:FCFF00:FF9900>Дуэль началась!</gradient>"
    subtitle: "&eУдачи!"
    fadeIn: 10
    stay: 60
    fadeOut: 20
  duel-ended:
    title: "<gradient:FCFF00:FF9900>Дуэль окончена!</gradient>"
    subtitle: "&eПобедитель: &a%winner%"
    fadeIn: 10
    stay: 60
    fadeOut: 20
  duel-timeout:
    title: "&cВремя истекло!"
    subtitle: "&eДуэль завершена без победителя"
    fadeIn: 10
    stay: 60
    fadeOut: 20

arena:
  # Максимальное время занятости арены (в минутах), после которого она будет принудительно освобождена
  max-occupation-time: 30

  # Максимальное расстояние от точек спавна, в пределах которого игрок считается на арене
  boundary-distance: 30

  # Игнорировать ли Y-координату при проверке границ (только для арен без областей восстановления)
  ignore-y-boundaries: true

  # Использовать ли безопасную телепортацию (поиск твердого блока)
  safe-teleport: true

  # Проверять ли границы мгновенно при движении игрока
  instant-boundary-check: true

# Настройки оптимизации
optimization:
  # Очищать ли инвентарь от ненужных предметов перед дуэлью (для уменьшения объема данных)
  clean-inventory-before-duel: false

  # Список материалов, которые следует удалить из инвентаря перед дуэлью
  materials-to-clean:
    - "DIRT"
    - "COBBLESTONE"
    - "SAND"
    - "GRAVEL"
    - "NETHERRACK"

  # Максимальное количество загружаемых чанков вокруг арены
  max-chunks-to-load: 9

  # Временно уменьшать дистанцию прорисовки во время дуэли
  reduce-view-distance: true

  # Временная дистанция прорисовки (чанков)
  temporary-view-distance: 3

  # Очищать сущности на аренах
  clean-arena-entities: true

  # Интервал очистки сущностей (в секундах)
  entity-cleanup-interval: 60

  # Максимальное количество арен, которые не будут повторно выбраны
  max-recent-arenas: 3

# Режим отладки (выводит дополнительную информацию в консоль)
debug: false
